name: windows-build
on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd   # весь job в CMD

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip wheel
          if exist requirements.txt (
            python -m pip install -r requirements.txt
          )
          python -m pip install pyinstaller

      - name: Clean
        run: |
          if exist build rmdir /s /q build
          if exist dist rmdir /s /q dist
          if exist buildspec rmdir /s /q buildspec
          del /f /q *.spec 2>nul

      - name: Build EXE (no icon)
        run: |
          pyinstaller --noconsole --onefile --clean --specpath buildspec --name "QRMobile" app\app_gui.py

      - name: Upload EXE (portable)
        uses: actions/upload-artifact@v4
        with:
          name: QRMobile-exe
          path: dist/QRMobile.exe
          if-no-files-found: error

      # ===== OPTIONAL: NSIS installer (только если есть build_scripts\installer.nsi) =====
      - name: Install NSIS (optional)
        if: hashFiles('build_scripts/installer.nsi') != ''
        run: choco install nsis -y --no-progress

      - name: Build Installer (NSIS, optional)
        if: hashFiles('build_scripts/installer.nsi') != ''
        working-directory: build_scripts
        run: |
          if not exist Output mkdir Output
          "C:\Program Files (x86)\NSIS\makensis.exe" installer.nsi

      - name: Upload Setup (optional)
        if: hashFiles('build_scripts/installer.nsi') != '' && always()
        uses: actions/upload-artifact@v4
        with:
          name: QRMobile-Setup
          path: build_scripts\Output\QRMobile-Setup.exe
          if-no-files-found: warn
